info:
  name: prometheus
  type: http
  seq: 7

http:
  method: GET
  url: http://localhost:8080/actuator/prometheus
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
